lst=['murali',1,'ashok','4522','kittu']
#append
lst.append('lakshmi')
print('appended',lst)
#clear
lst.clear()
print('clear',lst)
#copy
lst=['murali',1,'ashok','4522','kittu']
lst1=lst.copy()
print('copy',lst1)
#count
a=lst.count('ashok')
print('count',a)
#extend
lst2=['krishna',2,'kumar',1095,'thushith']
lst.extend(lst2)
print('extended',lst)
#index
lst=['murali',1,'ashok','4522','kittu']
i=lst.index('ashok')
print('index',i)
#insert
lst.insert(1,'lakshmi')
print('inserted',lst)
#pop
lst.pop()
print('poped',lst)
p=lst.pop(4)
print('indexed pop',lst)
#remove
lst.remove('ashok')
print('removed',lst)
#reverse
lst.reverse()
print('reveresed',lst)
#sort
lst=['murali','lakshmi','ashok']
lst.sort()
print('sorted',lst)
